#!/usr/bin/env bash
# Remove the leading './' from the script name
script_name=$(basename "$0")

# Check if an IP address is provided
if [ -z "$1" ]; then
  echo "Usage: $script_name {IP_ADDRESS}"
  exit 1
fi

# Ping the IP address 5 times
ping -c 5 "$1"
