#!/usr/bin/env bash
# Configures an Ubuntu server: localhost resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i 's/^127.*$/127.0.0.2 localhost/g' ~/hosts.new
sed -i 's/.*facebook.com/8.8.8.8 facebook.com/g' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
