#!/usr/bin/env bash
# Configures an Ubuntu server: localhost resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8
sed -i '/localhost/ s/.*/127.0.0.2 localhost/' /etc/hosts
sed -i '/facebook.com/ s/.*/8.8.8.8 facebook.com/' /etc/hosts
